# # Generated by the protocol buffer compiler.  DO NOT EDIT!
# # source: entity/stream_message_data_task.proto

# require 'google/protobuf'

# Google::Protobuf::DescriptorPool.generated_pool.build do
#   add_file(PWD + "/proto/entity/stream_message_data_task.proto", :syntax => :proto3) do
#     add_message "grpc.StreamMessageDataTask" do
#       optional :task_id, :string, 1
#       optional :data, :string,:repeated, 2
#     end
#   end
# end

# module Grpc
#   StreamMessageDataTask = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.StreamMessageDataTask").msgclass
# end


# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity/stream_message_data_task.proto

require 'google/protobuf'

# require 'entity/result_pb'


descriptor_data = "\n%entity/stream_message_data_task.proto\x12\x04grpc\x1a\x13\x65ntity/result.proto\"D\n\x15StreamMessageDataTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x1a\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x0c.grpc.ResultB\x08Z\x06.;grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["grpc.Result", "entity/result.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Grpc
  StreamMessageDataTask = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.StreamMessageDataTask").msgclass
end